var vm = new Vue({
    el: '#app',
    data: {
        isOnline:false,//是否正在直播
        activeIn:"",//校外教学点
        activeOut:"",//校内教学点
        dialogTableClassroom:false,//教室列表弹框
        dataList:[
            {
                "id":"12",
                "title":"智慧城市学院",
                "activeNum":3,
                "children":[
                    {uid:"121",major:'建筑智能化',className:"建筑智能化1班"},
                    {uid:"122",major:'建筑智能化',className:"建筑智能化2班"},
                    {uid:"123",major:'建筑智能化',className:"建筑智能化3班"},
                    {uid:"124",major:'建筑智能化',className:"建筑智能化4班"},
                    {uid:"125",major:'建筑智能化',className:"建筑智能化5班"},
                    {uid:"126",major:'建筑智能化',className:"建筑智能化6班"},
                ]
            },
            {
                "id":"13",
                "title":"物联网学院",
                "activeNum":3,
                "children":[
                    {uid:"131",major:'物联网工程',className:"物联网工程1班"},
                    {uid:"132",major:'物联网工程',className:"物联网工程2班"},
                    {uid:"133",major:'物联网工程',className:"物联网工程3班"},
                    {uid:"134",major:'物联网工程',className:"物联网工程4班"},
                    {uid:"135",major:'物联网工程',className:"物联网工程5班"},
                    {uid:"136",major:'物联网工程',className:"物联网工程6班"},
                ]
            },
            {
                "id":"14",
                "title":"物联网学院",
                "activeNum":3,
                "children":[
                    {uid:"131",major:'物联网工程',className:"物联网工程1班"},
                    {uid:"132",major:'物联网工程',className:"物联网工程2班"},
                    {uid:"133",major:'物联网工程',className:"物联网工程3班"},
                    {uid:"134",major:'物联网工程',className:"物联网工程4班"},
                    {uid:"135",major:'物联网工程',className:"物联网工程5班"},
                    {uid:"136",major:'物联网工程',className:"物联网工程6班"},
                ]
            },
            {
                "id":"15",
                "title":"物联网学院",
                "activeNum":3,
                "children":[
                    {uid:"131",major:'物联网工程',className:"物联网工程1班"},
                    {uid:"132",major:'物联网工程',className:"物联网工程2班"},
                    {uid:"133",major:'物联网工程',className:"物联网工程3班"},
                    {uid:"134",major:'物联网工程',className:"物联网工程4班"},
                    {uid:"135",major:'物联网工程',className:"物联网工程5班"},
                    {uid:"136",major:'物联网工程',className:"物联网工程6班"},
                ]
            },
            {
                "id":"16",
                "title":"物联网学院",
                "activeNum":3,
                "children":[
                    {uid:"131",major:'物联网工程',className:"物联网工程1班"},
                    {uid:"132",major:'物联网工程',className:"物联网工程2班"},
                    {uid:"133",major:'物联网工程',className:"物联网工程3班"},
                    {uid:"134",major:'物联网工程',className:"物联网工程4班"},
                    {uid:"135",major:'物联网工程',className:"物联网工程5班"},
                    {uid:"136",major:'物联网工程',className:"物联网工程6班"},
                ]
            },
            {
                "id":"17",
                "title":"物联网学院",
                "activeNum":3,
                "children":[
                    {uid:"131",major:'物联网工程',className:"物联网工程1班"},
                    {uid:"132",major:'物联网工程',className:"物联网工程2班"},
                    {uid:"133",major:'物联网工程',className:"物联网工程3班"},
                    {uid:"134",major:'物联网工程',className:"物联网工程4班"},
                    {uid:"135",major:'物联网工程',className:"物联网工程5班"},
                    {uid:"136",major:'物联网工程',className:"物联网工程6班"},
                ]
            },
            {
                "id":"18",
                "title":"物联网学院",
                "activeNum":3,
                "children":[
                    {uid:"131",major:'物联网工程',className:"物联网工程1班"},
                    {uid:"132",major:'物联网工程',className:"物联网工程2班"},
                    {uid:"133",major:'物联网工程',className:"物联网工程3班"},
                    {uid:"134",major:'物联网工程',className:"物联网工程4班"},
                    {uid:"135",major:'物联网工程',className:"物联网工程5班"},
                    {uid:"136",major:'物联网工程',className:"物联网工程6班"},
                ]
            },
            {
                "id":"19",
                "title":"物联网学院",
                "activeNum":3,
                "children":[
                    {uid:"131",major:'物联网工程',className:"物联网工程1班"},
                    {uid:"132",major:'物联网工程',className:"物联网工程2班"},
                    {uid:"133",major:'物联网工程',className:"物联网工程3班"},
                    {uid:"134",major:'物联网工程',className:"物联网工程4班"},
                    {uid:"135",major:'物联网工程',className:"物联网工程5班"},
                    {uid:"136",major:'物联网工程',className:"物联网工程6班"},
                ]
            },
            {
                "id":"13",
                "title":"物联网学院",
                "activeNum":3,
                "children":[
                    {uid:"131",major:'物联网工程',className:"物联网工程1班"},
                    {uid:"132",major:'物联网工程',className:"物联网工程2班"},
                    {uid:"133",major:'物联网工程',className:"物联网工程3班"},
                    {uid:"134",major:'物联网工程',className:"物联网工程4班"},
                    {uid:"135",major:'物联网工程',className:"物联网工程5班"},
                    {uid:"136",major:'物联网工程',className:"物联网工程6班"},
                ]
            },
        ],
        gridData:[
            {id:1,name:"汽车检测与维修技术-2021级汽车检测与维修技术一班"},
            {id:2,name:"汽车检测与维修技术-2021级汽车检测与维修技术2班"},
            {id:3,name:"汽车检测与维修技术-2021级汽车检测与维修技术3班"},
        ],
        selectKey:'',

    },
    methods: {
        collapseChange(val){
            console.log(val);
        },
        delItem(row){
            console.log(row);
        },
        showTable(){
            this.dialogTableClassroom = true;
        },
        selectClass(i){
            this.selectKey = i;
            console.log('指向');
            
        },
    },
    mounted(){


    }
})